---
swagger: "2.0"
info:
  description: "Service runs Risk checks against the applicant's profile. Returns\
    \ Approved/declined/Pended status or list of verId questions based on the channel\
    \ and existing customer flag."
  version: "1.0.0"
  title: "Risk Check"
  termsOfService: ""
basePath: "/v4/account-opening-risk-check"
schemes:
- "https"
paths:
  /riskCheck/{transactionId}:
    get:
      summary: "Runs risk checks against applicants profile."
      description: "Applicant's profile is verified against risk engine."
      operationId: "riskCheck"
      produces:
      - "application/json"
      parameters:
      - name: "transactionId"
        in: "path"
        required: true
        description: "TransactionId of the applicant created as a part of applicant\
          \ risk profile creation."
        type: "string"
      - name: "x-correlation-id"
        in: "header"
        type: "string"
        description: "Unique identifier for every service call."
        required: true
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/riskCheckResponse"
        400:
          description: "Bad request: - Invalid request headers.                  -\
            \ Invalid transactionId/applicantId                                  -\
            \ TransactionId and applicantId do not match."
          schema:
            $ref: "#/definitions/invalidVeridResponse"
        500:
          description: "Internal server error or service call to cashEdge fails."
definitions:
  invalidVeridResponse:
    type: "object"
    properties:
      errors:
        type: "array"
        items:
          type: "object"
          properties:
            code:
              type: "string"
              example: "ABCD123"
            reason:
              type: "string"
              example: "Invalid header ABCD."
  riskCheckResponse:
    type: "object"
    properties:
      status:
        type: "string"
        enum:
        - "APPROVED"
        - "PENDED"
        - "DECLINED"
        example: "Approved"
        description: "status of risk checks. This is an optional field as is not\
          \ available when veridDetails section is returned."
      description:
        type: "string"
        example: "Customer approved"
      link:
        type: "array"
        items:
          type: "object"
          properties:
            rel:
              type: "string"
              enum:
              - "NEXT"
              - "COMBINE-DECISION"
            href:
              type: "string"
            httpMethod:
              type: "string"
              enum:
              - "PUT"
              - "POST"
              - "GET"
              example: "PUT"
            accept:
              type: "string"
              example: "application/json"
            contentType:
              type: "string"
              example: "application/json"